# Generated by Django 5.2.2 on 2025-06-10 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scale_data', models.JSONField(help_text='Grade boundaries and descriptions')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Grading Scale',
                'verbose_name_plural': 'Grading Scales',
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('quiz', 'Quiz Template'), ('assignment', 'Assignment Template'), ('rubric', 'Rubric Template'), ('self_assessment', 'Self-Assessment Template')], max_length=30)),
                ('template_data', models.JSONField(help_text='Template structure and content')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Template',
                'verbose_name_plural': 'Assessment Templates',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('assignment_type', models.CharField(choices=[('business_plan', 'Business Plan'), ('swot_analysis', 'SWOT Analysis'), ('case_study', 'Case Study Analysis'), ('reflection', 'Reflection Paper'), ('presentation', 'Presentation'), ('project', 'Project Work'), ('research', 'Research Assignment')], max_length=30)),
                ('submission_format', models.CharField(choices=[('text', 'Text Only'), ('file', 'File Upload Only'), ('both', 'Text and File')], max_length=20)),
                ('max_file_size', models.IntegerField(default=10485760, help_text='Maximum file size in bytes (default 10MB)')),
                ('allowed_file_types', models.JSONField(blank=True, default=list, help_text='Allowed file extensions')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=100)),
                ('rubric', models.JSONField(blank=True, default=dict, help_text='Grading rubric')),
                ('is_peer_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_count', models.IntegerField(default=3, help_text='Number of peer reviewers per submission')),
                ('review_criteria', models.JSONField(help_text='Criteria for peer review')),
                ('review_deadline', models.DateTimeField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assessments.assignment')),
            ],
            options={
                'verbose_name': 'Peer Review',
                'verbose_name_plural': 'Peer Reviews',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score to pass (percentage)')),
                ('is_randomized', models.BooleanField(default=False, help_text='Randomize question order')),
                ('show_results', models.BooleanField(default=True, help_text='Show results immediately after completion')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for multiple choice questions')),
                ('correct_answer', models.TextField(help_text='Correct answer or answer key')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('points', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_points', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in final grade', max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='assessments.assignment')),
            ],
            options={
                'verbose_name': 'Rubric Criteria',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['assignment', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('personal_initiative', 'Personal Initiative'), ('innovation', 'Innovation and Creativity'), ('goal_setting', 'Goal Setting'), ('planning', 'Planning Skills'), ('financial_literacy', 'Financial Literacy'), ('leadership', 'Leadership Skills')], max_length=30)),
                ('questions', models.JSONField(help_text='Self-assessment questions and scoring')),
                ('scoring_guide', models.JSONField(help_text='How to interpret scores')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self Assessment',
                'verbose_name_plural': 'Self Assessments',
            },
        ),
    ]
