# Generated by Django 5.2.2 on 2025-06-10 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text Content'), ('video', 'Video'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('document', 'Document'), ('interactive', 'Interactive Content'), ('image', 'Image'), ('infographic', 'Infographic')], max_length=30)),
                ('content', models.TextField(blank=True, help_text='Text content or description')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='content/')),
                ('external_url', models.URLField(blank=True, help_text='External resource URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional content metadata')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Content tags for search')),
                ('is_public', models.BooleanField(default=False, help_text='Available to all users')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('library_type', models.CharField(choices=[('templates', 'Business Templates'), ('case_studies', 'Case Studies'), ('tools', 'Business Tools'), ('presentations', 'Presentations'), ('videos', 'Video Library'), ('documents', 'Documents')], max_length=30)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Library',
                'verbose_name_plural': 'Content Libraries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='Detailed instructions for the exercise')),
                ('exercise_type', models.CharField(choices=[('case_study', 'Case Study Analysis'), ('group_work', 'Group Work'), ('individual_reflection', 'Individual Reflection'), ('scamper', 'SCAMPER Technique'), ('swot_analysis', 'SWOT Analysis'), ('business_plan', 'Business Plan Development'), ('brainstorming', 'Brainstorming Session'), ('role_play', 'Role Playing'), ('simulation', 'Business Simulation')], max_length=30)),
                ('exercise_data', models.JSONField(help_text='Exercise-specific data structure')),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('max_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_exercises', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Interactive Exercise',
                'verbose_name_plural': 'Interactive Exercises',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('template', 'Template'), ('tool', 'Business Tool'), ('external_link', 'External Link'), ('video', 'Video Resource'), ('audio', 'Audio Resource'), ('infographic', 'Infographic'), ('checklist', 'Checklist')], max_length=30)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('enrolled', 'Enrolled Students Only'), ('premium', 'Premium Members Only')], default='public', max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='content.contentitem')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Content',
                'verbose_name_plural': 'Lesson Contents',
                'ordering': ['lesson', 'sort_order'],
                'unique_together': {('lesson', 'content_item')},
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='content.contentitem')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.contentlibrary')),
            ],
            options={
                'verbose_name': 'Library Item',
                'verbose_name_plural': 'Library Items',
                'ordering': ['library', 'sort_order'],
                'unique_together': {('library', 'content_item')},
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='courses.lesson')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='content.resource')),
            ],
            options={
                'verbose_name': 'Lesson Resource',
                'verbose_name_plural': 'Lesson Resources',
                'ordering': ['lesson', 'sort_order'],
                'unique_together': {('lesson', 'resource')},
            },
        ),
    ]
